BINARIES = listing_05.03 \
           listing_05.04 \
           listing_05.05 \
           listing_05.06 \
           listing_05.07 \
           listing_05.08 \
           listing_05.09 \
           listing_05.10 \
           listing_05.12 \
           listing_05.13

OBJECTS = listing_05.01.o \
          listing_05.02.o

ERRORS = listing_05.11.err

include ../make.mk
