BINARIES =

OBJECTS = listing_07.01.o \
          listing_07.02.o \
          listing_07.03.o \
          listing_07.07.o \
          listing_07.09.o \
          listing_07.12.o \
          listing_07.13.o \
          listing_07.15.o

ERRORS = listing_07.04.err \
         listing_07.05.err \
         listing_07.06.err \
         listing_07.08.err \
         listing_07.10.err \
         listing_07.11.err \
         listing_07.14.err \
         listing_07.16.err \
         listing_07.17.err \
         listing_07.18.err \
         listing_07.19.err \
         listing_07.20.err \
         listing_07.21.err

include ../make.mk
