BINARIES = listing_04.01 \
           listing_04.02 \
           listing_04.03 \
           listing_04.04 \
           listing_04.05 \
           listing_04.06 \
           listing_04.07

OBJECTS = listing_04.08.o \
          listing_04.09.o \
          listing_04.11.o \
          listing_04.12.o \
          listing_04.13.o \
          listing_04.14.o

ERRORS = listing_04.10.err \
         listing_04.15.err \
         listing_04.16.err

include ../make.mk
