BINARIES =

OBJECTS = listing_09.02.o \
          listing_09.09.o

ERRORS = listing_09.01.err \
         listing_09.03.err \
         listing_09.04.err \
         listing_09.05.err \
         listing_09.06.err \
         listing_09.07.err \
         listing_09.08.err \
         listing_09.10.err \
         listing_09.11.err \
         listing_09.12.err \
         listing_09.13.err

include ../make.mk
