BINARIES =

OBJECTS = listing_c.01.o

ERRORS = listing_c.02.err \
         listing_c.03.err \
         listing_c.04.err \
         listing_c.05.err \
         listing_c.06.err \
         listing_c.07.err \
         listing_c.08.err \
         listing_c.09.err \
         listing_c.10.err

include ../make.mk
