BINARIES = listing_06.02

OBJECTS = listing_06.01.o \
          listing_06.03.o \
          listing_06.04.o \
          listing_06.05.o \
          listing_06.06.o \
          listing_06.07.o \
          listing_06.11.o \
          listing_06.13.o

ERRORS = listing_06.08.err \
         listing_06.09.err \
         listing_06.10.err \
         listing_06.12.err

include ../make.mk
