BINARIES =

OBJECTS = listing_08.02.o \
          listing_08.03.o \
          listing_08.05.o \
          listing_08.08.o \
          listing_08.10.o \
          listing_08.12.o \
          listing_08.13.o

ERRORS = listing_08.01.err \
         listing_08.04.err \
         listing_08.06.err \
         listing_08.07.err \
         listing_08.09.err \
         listing_08.11.err

include ../make.mk
